config/routes.rb
Recipes::Application.routes.draw do
  resources :mikroposts

  resources :users

  root :to => 'users#index'

end

app/models/mikropost.rb
class Mikropost < ActiveRecord::Base
  attr_accessible :content, :user_id

  belongs_to :user

  validates :content, :length => { :maximum => 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  has_many :mikroposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mikroposts_controller.rb
class MikropostsController < ApplicationController
  # GET /mikroposts
  # GET /mikroposts.json
  def index
    @mikroposts = Mikropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @mikroposts }
    end
  end

  # GET /mikroposts/1
  # GET /mikroposts/1.json
  def show
    @mikropost = Mikropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @mikropost }
    end
  end

  # GET /mikroposts/new
  # GET /mikroposts/new.json
  def new
    @mikropost = Mikropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @mikropost }
    end
  end

  # GET /mikroposts/1/edit
  def edit
    @mikropost = Mikropost.find(params[:id])
  end

  # POST /mikroposts
  # POST /mikroposts.json
  def create
    @mikropost = Mikropost.new(params[:mikropost])

    respond_to do |format|
      if @mikropost.save
        format.html { redirect_to @mikropost, :notice => 'Mikropost was successfully created.' }
        format.json { render :json => @mikropost, :status => :created, :location => @mikropost }
      else
        format.html { render :action => "new" }
        format.json { render :json => @mikropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mikroposts/1
  # PUT /mikroposts/1.json
  def update
    @mikropost = Mikropost.find(params[:id])

    respond_to do |format|
      if @mikropost.update_attributes(params[:mikropost])
        format.html { redirect_to @mikropost, :notice => 'Mikropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @mikropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mikroposts/1
  # DELETE /mikroposts/1.json
  def destroy
    @mikropost = Mikropost.find(params[:id])
    @mikropost.destroy

    respond_to do |format|
      format.html { redirect_to mikroposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mikroposts_helper.rb
module MikropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mikroposts/_form.html.erb
<%= form_for(@mikropost) do |f| %>
  <% if @mikropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mikropost.errors.count, "error") %> prohibited this mikropost from being saved:</h2>

      <ul>
      <% @mikropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mikroposts/edit.html.erb
<h1>Editing mikropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @mikropost %> |
<%= link_to 'Back', mikroposts_path %>

app/views/mikroposts/index.html.erb
<h1>Listing mikroposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mikroposts.each do |mikropost| %>
  <tr>
    <td><%= mikropost.content %></td>
    <td><%= mikropost.user_id %></td>
    <td><%= link_to 'Show', mikropost %></td>
    <td><%= link_to 'Edit', edit_mikropost_path(mikropost) %></td>
    <td><%= link_to 'Destroy', mikropost, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mikropost', new_mikropost_path %>

app/views/mikroposts/new.html.erb
<h1>New mikropost</h1>

<%= render 'form' %>

<%= link_to 'Back', mikroposts_path %>

app/views/mikroposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @mikropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @mikropost.user_id %>
</p>


<%= link_to 'Edit', edit_mikropost_path(@mikropost) %> |
<%= link_to 'Back', mikroposts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>